### PR TITLE
Logo link fix

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by estenberg** [comment]
My browser does not render https://hosted.mender.io/ui/assets/img/loginlogo.png

Maybe we should find a better one? Likely in mender.io somewhere.

Also, unfortunately, this will probably apply to *all* the repositories.. so maybe a redirect would be easier/better?

**Comment by merlin-northern** [comment]
> My browser does not render https://hosted.mender.io/ui/assets/img/loginlogo.png
> 
> Maybe we should find a better one? Likely in mender.io somewhere.
> 
> Also, unfortunately, this will probably apply to _all_ the repositories.. so maybe a redirect would be easier/better?

wow, something is not right, I cant find the repo I took that from, also many other repos have the logo broken, as you pointed out. I have no idea, let me check.

**Comment by oleorhagen** [comment]
@merlin close?

**Comment by merlin-northern** [comment]
> @Merlin close?

the logo is still broken. I wonder when I will have time to get back to it.

**Pull request closed without merging**
