### PR TITLE
fix: Reader cannot parse files with zst compression

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Review by kacf — APPROVED** [review]
Thanks, change looks good to me!

Please don't use `--fast` option on client pipelines, though. It omits nearly all client tests.

**Comment by kjaskiewiczz** [comment]
@alfrunes looks good; look at the comment [here](https://northerntech.atlassian.net/browse/MEN-6617?focusedCommentId=98133) ;)

**Comment by kjaskiewiczz** [comment]
https://github.com/mendersoftware/mender-artifact/pull/515 @alfrunes same as yours (almost), but with green basic pipeline and running full pipeline (without --fast option)

**Comment by alfrunes** [comment]
> Please don't use `--fast` option on client pipelines, though. It omits nearly all client tests.

I used the fast option because this code path clearly is not tested.

**Comment by kacf** [comment]
> I used the fast option because this code path clearly is not tested.

Ok, fair point. 🙂

**Pull request closed without merging**
