### PR TITLE
Add support for compressing artifacts using LZMA

### PR DESCRIPTION
**Pull request by spencercw**
This depends on PR #150, which I have merged into this PR for the time being. Other than that I think it should be good to go. I don't have any hardware to hand so I can't test a real deployment, but the CLI tool can read the artifact back so I can't see any reason why it wouldn't work.

### CODE REVIEW

**Comment by spencercw** [comment]
Rebased on master with #150 applied and improved the test coverage a little.

**Comment by kacf** [comment]
Isn't github.com/smira/lzma using the LZMA v1 algorithm? I'm not sure if this is a good addition to Mender, since the algorithm has been superseded by LZMA v2 (xz in particular), and we also have to think about binary size of the client.

**Comment by spencercw** [comment]
Hi Kristian,

Re. LZMA v1, that's fair. I did look at github.com/ulikunitz/xz (which seems to be the 'popular' one), but it says on the GitHub page that it is under development and the API is not stable, so I passed that one by. There are other options available which I could look into.

Binary size is a bit of a trade off. In my use case, smaller update files are more important because updates will be deployed over a metered mobile data connection. Perhaps it could be added as a PACKAGECONFIG option to the mender-artifact recipe, so it can be turned off to reduce the binary size if it is unwanted?

**Comment by kacf** [comment]
Yes, that would be acceptable, `no-lzma` tag for `go build` or something like that.

Another solution would be to pipe data to the system `xz` command instead of using a library, and have it perform the compression and decompression for us. This would give even more space savings, and I think `xz` is usually present in most configurations. But that means more implementation work, obviously.

**Comment by spencercw** [comment]
I tend to prefer using libraries where possible, and I wouldn't expect there to be much size difference between invoking an executable and dynamically linking to the lzma library. The xz utility seems to dynamically link to liblzma, so:
- If xz is already installed, there is no significant size penalty since the lib is already there.
- If xz is not installed, then the size penalty would be for just liblzma, rather than xz+liblzma.

Either way, we're going to need to make sure it's available on the build server. By the looks of things I think I can just add it to the apt-get in travis.yml.

**Comment by kacf** [comment]
Yes, if you can dynamically link to liblzma using a C binding, that would be even better.

**Comment by spencercw** [comment]
So I've found two existing wrappers for liblzma: [github.com/danielrh/go-xz](https://github.com/danielrh/go-xz) and [github.com/remyoudompheng/go-liblzma](https://github.com/remyoudompheng/go-liblzma). Amazingly, they both have the exact same bug where if the source reader returns `nBytes > 0 && err == EOF` on the final successful read (instead of `nBytes == 0 && err == EOF` *after* the last successful read) then the decompressed output can be truncated.

I have raised a PR for the first, which as yet hasn't been acknowledged. There is already a PR open on the second, but it hasn't had any activity for some time.

On the whole, the code for the second seems a bit tidier and better tested so, this issue aside, I think that would be the one to use. Assuming there is no activity in the next week or so, I could fork it (or perhaps you would prefer to fork it under the mendersoftware account?) and merge the fix in there. What do you reckon?

**Comment by kacf** [comment]
> So I've found two existing wrappers for liblzma: [github.com/danielrh/go-xz](https://github.com/danielrh/go-xz) and [github.com/remyoudompheng/go-liblzma](https://github.com/remyoudompheng/go-liblzma). Amazingly, they both have the exact same bug where if the source reader returns `nBytes > 0 && err == EOF` on the final successful read (instead of `nBytes == 0 && err == EOF` _after_ the last successful read) then the decompressed output can be truncated.

Ok, but does this actually happen in practice? I don't recall the exact behavior, but I would assume that `io.Reader` returns `nBytes == 10 && err == nil` if there are 10 bytes left, even if those are the last 10 bytes. And then it would return `err == EOF` afterwards. I could be wrong though.

> I have raised a PR for the first, which as yet hasn't been acknowledged. There is already a PR open on the second, but it hasn't had any activity for some time.
> 
> On the whole, the code for the second seems a bit tidier and better tested so, this issue aside, I think that would be the one to use. Assuming there is no activity in the next week or so, I could fork it (or perhaps you would prefer to fork it under the mendersoftware account?) and merge the fix in there. What do you reckon?

Assuming it's really needed (ref previous comment), merging the PR is obviously the most desirable, but a fork is ok too. Just let me know what the result is, and I can create the mendersoftware clone if needed.

**Comment by spencercw** [comment]
> Ok, but does this actually happen in practice? I don't recall the exact behavior, but I would assume that io.Reader returns nBytes == 10 && err == nil if there are 10 bytes left, even if those are the last 10 bytes. And then it would return err == EOF afterwards. I could be wrong though.

Yes, the tar reader returns an 'early' EOF. Either way is acceptable according to the io.Reader documentation, which is just inviting bugs IMO. By coincidence, the test image I'm using happens to trigger the faulty behaviour and mender-artifact can't read back the artifact it has just written.

I'm not in any particular rush so I will just leave it a while to see if the PR gets merged.

**Comment by kacf** [comment]
Alright, sounds good!

**Comment by kacf** [comment]
It's done! We now have a new fork at https://github.com/mendersoftware/go-liblzma with your PR merged!

**Comment by spencercw** [comment]
Nice one. Lets try this one on for size.

I tried uploading an lzma-compressed artifact to our hosted Mender account but unsurprisingly it got a bit upset. Not really sure how best to tackle that.
"Artifact couldn't be uploaded. reading artifact error: reader: found unexpected file in artifact: header.tar.xz... [Request ID: 22857036]"

**Comment by kacf** [comment]
Yes, the deployments service would need to have its mender-artifact vendor library updated. There a couple of things that need to happen where, which I have described in [MEN-761](https://tracker.mender.io/browse/MEN-761). @spencercw, I don't see your name in the list of users there. Perhaps you want to create one?

**Comment by dellgreen** [comment]
See https://tracker.mender.io/browse/MEN-761 for existing background work we have done on this which may help

**Comment by spencercw** [comment]
Thanks, I wasn't aware of that other ticket. I'm out of the office for the rest of the year but I might be able to help with some of the outstanding changes when I get back.

**Comment by oleorhagen** [comment]
@spencercw I merged this PR a bit pre-maturely, thinking that vendoring updates would not prove to be a problem. There is not a problem with the PR per-se, but the CGO dependency will take a little bit of work to get working with our deployments service. This should not be a lot of work, but too much for this last hour on the job, before the holidays. I promise that this will be the first thing I look into next year! 
Merry Christmas :)

**Comment by spencercw** [comment]
Ok no worries, thanks for the update. Merry Christmas :)

**Comment by spencercw** [comment]
FYI, the go-liblzma PR has now been merged upstream so we could drop the mendersoftware fork if you like.

**Pull request merged**
