### PR TITLE
3.7.x: Update LICENSE copyright year to 2022

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :fireworks:

**Comment by lluiscampos** [comment]
The QEMU build now [passes](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/2257473916).

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
@mender-test-bot  cherry-pick to:
* 3.6.x

**Comment by lluiscampos** [comment]
@mender-test-bot cherry-pick to:
* 3.7.x

**Pull request merged**
