### PR TITLE
cli: Move dump command into Artifact creation category.

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
From:
```
$ ./mender-artifact --help
(...)
COMMANDS:
   dump     Dump contents from Artifacts
   help, h  Shows a list of commands or help for one command

   Artifact creation and validation:
     write     Writes artifact file.
     read      Reads artifact file.
     validate  Validates artifact file.

   Artifact modification:
     sign     Signs existing artifact file.
     modify   Modifies image or artifact file.
     cp       cp <src> <dst>
     cat      cat [artifact|sdimg|uefiimg]:<filepath>
     install  install -m <permissions> <hostfile> [artifact|sdimg|uefiimg]:<filepath> or install -d [artifact|sdimg|uefiimg]:<directory>
     rm       rm [artifact|sdimg|uefiimg]:<filepath>
```

to:
```
$ ./mender-artifact --help
(...)
COMMANDS:
   help, h  Shows a list of commands or help for one command

   Artifact creation and validation:
     write     Writes artifact file.
     read      Reads artifact file.
     validate  Validates artifact file.
     dump      Dump contents from Artifacts

   Artifact modification:
     sign     Signs existing artifact file.
     modify   Modifies image or artifact file.
     cp       cp <src> <dst>
     cat      cat [artifact|sdimg|uefiimg]:<filepath>
     install  install -m <permissions> <hostfile> [artifact|sdimg|uefiimg]:<filepath> or install -d [artifact|sdimg|uefiimg]:<directory>
     rm       rm [artifact|sdimg|uefiimg]:<filepath>
```

**Comment by oleorhagen** [comment]
Hmm, not sure I agree here. How is this creation or validation?

**Comment by lluiscampos** [comment]
How is `read` validation?

I see your point - I don't like it neither. What if we move `read` and `dump` into a new category "Artifact inspection"?

What I hope we agree is that it look pretty bad being the only un-categorized command, and hence being listed before the rest (which are more important).

**Comment by oleorhagen** [comment]
> How is `read` validation?
> 

It's not a perfect fit, but it actually fails if the Artifact is misformed.

> I see your point - I don't like it neither. What if we move `read` and `dump` into a new category "Artifact inspection"?
> 

Tis' I like the sound of. Thinking about it some more, I actually think it's perfect! Let's!

> What I hope we agree is that it look pretty bad being the only un-categorized command, and hence being listed before the rest (which are more important).

Yes, I understand where this PR came from, and I like it.

Let's just do it proper

**Comment by lluiscampos** [comment]
New output:

```
$ ./mender-artifact --help
(...)
COMMANDS:
   help, h  Shows a list of commands or help for one command

   Artifact creation and validation:
     write     Writes artifact file.
     validate  Validates artifact file.

   Artifact inspection:
     read  Reads artifact file.
     dump  Dump contents from Artifacts

   Artifact modification:
     sign     Signs existing artifact file.
     modify   Modifies image or artifact file.
     cp       cp <src> <dst>
     cat      cat [artifact|sdimg|uefiimg]:<filepath>
     install  install -m <permissions> <hostfile> [artifact|sdimg|uefiimg]:<filepath> or install -d [artifact|sdimg|uefiimg]:<directory>
     rm       rm [artifact|sdimg|uefiimg]:<filepath>
```

**Comment by oleorhagen** [comment]
Beautiful :medal_sports:

**Review by oleorhagen — APPROVED** [review]

**Pull request merged**
