### PR TITLE
pref: Use best gzip compression by default

### PR DESCRIPTION
**Pull request by merlin-northern**
Changelog: Title
Ticket: MEN-6249
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Review by kacf — APPROVED** [review]
I would say in the changelog "Use best **gzip** compression by default".

I can't think of any ill effects this would have. Compression time might be marginally slower, but in my experience it doesn't have a large effect on gzip.

**Comment by merlin-northern** [comment]
> Use best **gzip** compression by default

fixed.

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by oleorhagen** [comment]
@kacf but is it really a minor bump this?

**Comment by kacf** [comment]
Oh, I missed that. You're right, I think this should be "fix".

**Comment by merlin-northern** [comment]
> Oh, I missed that. You're right, I think this should be "fix".

no problema. fix it is.

**Comment by oleorhagen** [comment]
> > Oh, I missed that. You're right, I think this should be "fix".
> 
> no problema. fix it is.

We also have the `perf` tag. But no strong opinions here.

**Comment by merlin-northern** [comment]
> perf

I had to rebase anyways, so moved to perf :)

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline sugar pretty please

**Pull request merged**
