### PR TITLE
Cherry men 4502/3.5.x

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by kacf** [comment]
Slightly less concerned about this one, since it is a more recent series, and still at ".0". (ref [this comment](https://github.com/mendersoftware/mender-artifact/pull/333#issuecomment-800058392))

**Comment by oleorhagen** [comment]
:green_circle: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/271116346

**Comment by oleorhagen** [comment]
https://github.com/mendersoftware/mender-artifact/pull/334#issuecomment-800836439

Nothing has changed since this pipe, just needed to retrigger the repo pipeline.

Merging.

**Pull request merged**
