### PR TITLE
chore: coveralls publish fix

### PR DESCRIPTION
**Pull request by kjaskiewiczz**
(cherry picked from commit 6c5b99cb25c480440c2bf5627e3bae7fab4e4a22)

### CODE REVIEW

**Comment by merlin-northern** [comment]
you need [this one](https://github.com/mendersoftware/mender-artifact/pull/438/files) to pass the tests

**Comment by kacf** [comment]
Unfortunately, I think we need the whole pipeline for this. I already tried this fix in https://github.com/mendersoftware/mender-artifact/pull/486 and failed. It became a time sink, so I left it alone at the time, since it's only 3.8.x. Is there a rush to get this in?

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Comment by kjaskiewiczz** [comment]
closing, since we already work on the fix here - https://github.com/mendersoftware/mender-artifact/pull/486

**Pull request closed without merging**
