### PR TITLE
ci: Update jobs tags for new runners

### PR DESCRIPTION
**Pull request by oldgiova**
Ticket: QA-493

### CODE REVIEW

**Review by merlin-northern — APPROVED** [review]
lgtm

**Review by kacf — APPROVED** [review]
I'll just run this quickly through the CI with a minimum test set.

**Comment by kacf** [comment]
Hmm, I don't understand [the error](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/4091121735). It does not look related. I'm launching a [new build](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/834799083), together with a pure [3.3.x build](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/834798431), just to compare.

**Comment by kacf** [comment]
Still, the error eludes me. I will log into a build host to see what's going on.

**Comment by kacf** [comment]
Alright, I believe I have identified the issue. I'm retrying together with https://github.com/mendersoftware/mender-connect/pull/99 and https://github.com/mendersoftware/meta-mender/pull/1936.

**Pull request merged**
