### PR TITLE
Do not close the pipe in TestCopyFromStdin twice

### PR DESCRIPTION
**Pull request by lluiscampos**
Port bugfix to 3.1.x

This should have been ported between beta and final 3.1.0... But anyway, let's get it in now so that can be part of 3.1.1

### CODE REVIEW

**Comment by lluiscampos** [comment]
@oleorhagen ^

**Comment by oleorhagen** [comment]
I don't understand why it needs to be in the release?

**Comment by oleorhagen** [comment]
Are the builds failing?

**Comment by lluiscampos** [comment]
The release build "pass", because they don't run unit tests. And I found this out now as the tests are failing for the official Debian packages build.

No problem, I have added it as a patch and we will drop the patch in 3.0.1

**Pull request merged**
