### PR TITLE
[Cherry] MEN-4502 3.4.x

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by kacf** [comment]
I would consider this a quite risky bug fix for a patch release, it's quite intrusive. Do we have a strong incentive to backport it?

**Comment by oleorhagen** [comment]
> I would consider this a quite risky bug fix for a patch release, it's quite intrusive. Do we have a strong incentive to backport it?

Well, you know the bug as well as I do, and if you don't think it's worthwhile, then I'm sure it's not.

I initially thought it could be pretty confusing, and the bug is pretty unrelated to the other functionality of `mender-artifact`.

But your call

**Comment by kacf** [comment]
I think my vote would be to omit it. It's not really a critical fix, I'd rather avoid the risk for this branch if we can.

**Comment by oleorhagen** [comment]
Closed: Decided the port is not critical

**Pull request closed without merging**
