### PR TITLE
MEN-2745: 'mender-artifact cp' now requires '-' in order to read stdin

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: Title

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
Now, mender-artifact requires the '-' on the command line in order to read from stdin. There is no check whether or not data is pending on stdin, so empty stdin will now lock. But that is not too surprising I think?

**Comment by kacf** [comment]
No, that is how I would expect it to work. And it allows the rare, but occasionally useful use case of typing something directly into the pipe.

**Comment by oleorhagen** [comment]
@kacf , the tests botched codecov for some reason.... Force, or rerun?

**Comment by kacf** [comment]
Nah, tiny change, coverage would not make a difference here anyway.

**Comment by kacf** [comment]
Thanks for the quick handling!

**Pull request merged**
